#  Please refer to the wiki(https://github.com/nlef/moonraker-telegram-bot/wiki) for detailed information on how to configure the bot

[bot]
server: localhost
bot_token: AweSomeBotToken
chat_id: 0

[camera]
host: http://localhost:8080/?action=stream
type: mjpeg

#[progress_notification]
#percent: 5
#height: 5
#time: 600

#[timelapse]
#cleanup: true
#height: 0.2
#time: 60
#target_fps: 15
#min_lapse_duration: 10
#max_lapse_duration: 60

[bot]
server: localhost
#   This is the adress, where the moonraker of the desired printer is located at. 
#   In most cases it will be 'localhost'. Alternatively, an ip:port, as in 192.168.0.19:7125 can be entered, 
#   if you are running multiple moonraker instances on the machine, or if the bot is located not on the printer itself.
#   This value is not validated automatically.
#   If you are running ssl, it should be yourcooldomain.xyz:ssl_poort, if certificate validation is enabled
bot_token: 8571109142:AAH_SqWGPIFN6iCZH0xyxE5ViusjV0LdQbM
#   This is the bot token. Please keep it safe and do not post it online.
#   Only the chat with the correct chat_id can send/receive commands to/from the bot.
#   Alternatively can be stored in a file. See [secrets] section.
#   This value is not validated automatically.
chat_id: VZ235
#   This is the ID of the chat, where the bot is supposed to be able to send updates to. 
#   Alternatively can be stored in a file. See [secrets] section.
#   This value should be an integer.
#ssl: False
#   This enables ssl for the moonraker connection.
#   Default is to omit this.
#   This value should be boolean.
#ssl_verify: True
#   If ssl is enabled, you can enable or disable certificate verification.
#   Default is true.
#   This value should be boolean.
#api_url: https://api.telegram.org/bot
#   If you need it, you can specify a custom url for the telegram API.
#   This value is not validated automatically.
#socks_proxy: 192.168.0.22:1080
#   If needed, you can configure the bot to use a socks5 proxy.
#   This value is not validated automatically.
#user: root
#   If you have moonraker authorization enabled, you can enter the user and password here.
#   My advice is to not expose your printer to the internet, but I am not your mother.
#   Alternatively can be stored in a file. See [secrets] section.
#   This value is not validated automatically.
#password: qwerty
#   The password is stored in plain text.
#   Alternatively can be stored in a file. See [secrets] section.
#   This value is not validated automatically.
#api_token: 86c4841ec730415da0a66064ceeaa99c
#   As an alternative to the password you can use a token.
#   Alternatively can be stored in a file. See [secrets] section.
#   This value is not validated automatically.
#light_device: leds
#   This is the power device in moonraker, to which the lights of the printer/chamber are connected to.
#   If you do not have lights/have no need to cycle them, skip this parameter.
#   Default is to omit this.
#   This can be a klipper output_pin or a macro as well. Refer to moonrakers "klipper_device" documentation.
#   This parameter will be derpeciated in coming updates.
#power_device: power
#   This is the power device in moonraker, to which the power of the printer slave boards are connected to.
#   A typical usage scenario is to shutdown power to the MCUs, but not to disable the host on which klipper is running.
#   If you do not have such a setup, skip this.
#   Default is to omit this.
#   This parameter will be derpeciated in coming updates.
#debug: false
#   This enables extensive logging. Only use it for debugging/troubleshooting.
#   Default is to omit this/false.
#   This value should be boolean.
#upload_path: myfolder/mysubfolder
#   This determines, to which folder the bot will upload the gcodes sent to it. 
#   Default is to use the base gcode folder.
#   Any path entered is relative from the klippers gcode folder.
#   This value is not validated automatically.
